# Generated by Django 5.2.6 on 2025-09-06 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='subscription',
            name='unique_active_subscription_per_user',
        ),
    ]
